name: Test with submission

on:
  push:
    tags:
      - sub.**

jobs:
  test-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: Submission
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.2
        with:
          path: Submission
          
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Check out tests private repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.AUTOGRADER_REPO }}
          token: ${{ secrets.PAT }}
          path: Autograder

      - name: Run test
        env:
          MODIFIED_FILES : ${{ steps.changed-files.outputs.all_modified_files }}
          GITHUB_USER : ${{ github.actor }}
        run: (cd Autograder/Common; bash autograder.sh Project1 >> Templates/test-failure.md)
        
      - name: Failure message
        if: failure()
        uses: machine-learning-apps/pr-comment@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: Autograder/Common/Templates/test-failure.md

      - name: Success message
        uses: machine-learning-apps/pr-comment@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: Autograder/Common/Templates/test-success.md
